INSERT INTO JDBC_HOMEWORK.DOG (NAME, BREED, OWNER_ID)
VALUES ('Puppy', 'Poodle', 3);

INSERT INTO JDBC_HOMEWORK.DOG (NAME, BREED, OWNER_ID)
VALUES ('Wolf', 'Husky', 2);

INSERT INTO JDBC_HOMEWORK.DOG (NAME, BREED, OWNER_ID)
VALUES ('Fluffy', 'Pomeranian', 1);