INSERT INTO JDBC_HOMEWORK.OWNER (NAME, SEX, CITY, STREET, POSTCODE)
VALUES ('Anna', 'FEMALE', 'London', 'Queens', 'SW1 1AB');
INSERT INTO JDBC_HOMEWORK.OWNER (NAME, SEX, CITY, STREET, POSTCODE)
VALUES ('Mary', 'FEMALE', 'Slough', 'High Street', 'AR1 1RA');
INSERT INTO JDBC_HOMEWORK.OWNER (NAME, SEX, CITY, STREET, POSTCODE)
VALUES ('John', 'MALE', 'Warsaw', 'Polnocna', '00-123');

